{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/part-of: helix-core
    app.kubernetes.io/managed-by: {{ .Release.Service }}
automountServiceAccountToken: true
{{- end }}
