#!/usr/bin/env python3
"""Canonical global substrate tool — see ~/shared/substrate/SUBSTRATE_PORTING_GUIDE.md.
Project-specific config in the CONFIG block below.

Generate the agent context pack for this project.

Outputs (all derived from PROJECT_STATE.json and the canonical docs):
  docs/context/AGENT_CONTEXT.md  - short "read me first" orientation. An
                                   AUTO region (regenerated from PROJECT_STATE)
                                   plus a preserved HUMAN region for prose.
  docs/context/SOURCE_MAP.md     - classification of the indexed corpus
                                   against PROJECT_STATE's canonical/historical
                                   doc lists.
  llms.txt                       - llms.txt-standard curated link index.
  llms-full.txt                  - full concatenation of canonical docs PLUS
                                   the active feature packet(s) for complete
                                   single-shot LLM ingestion.
  docs/context/.contextpack.hash - freshness marker over the pack inputs.

Improvement over prior versions:
  llms-full.txt now ALSO includes each active feature packet's files
  (requirements.md, design.md, tasks.md, acceptance.md, status.json), so a
  single-shot ingest gives an agent everything needed to continue work without
  a separate read pass over the feature directory.

Usage:
  python tools/context/build_context_pack.py
  python tools/context/build_context_pack.py --check   # exit 1 if stale

Stdlib only.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# CONFIG — edit this block when porting to a new project.
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]

# Output paths (relative to REPO_ROOT)
CTX        = REPO_ROOT / "docs" / "context" / "AGENT_CONTEXT.md"
SOURCE_MAP = REPO_ROOT / "docs" / "context" / "SOURCE_MAP.md"
LLMS       = REPO_ROOT / "llms.txt"
LLMS_FULL  = REPO_ROOT / "llms-full.txt"
HASH_FILE  = REPO_ROOT / "docs" / "context" / ".contextpack.hash"

# Input paths
STATE     = REPO_ROOT / "PROJECT_STATE.json"
INDEX_JSON = REPO_ROOT / "docs" / "DOCUMENT_INDEX.json"

# The 5 canonical files expected inside every feature packet directory.
# PORTING: if your packet convention differs, adjust this tuple.
PACKET_FILES = (
    "requirements.md",
    "design.md",
    "tasks.md",
    "acceptance.md",
    "status.json",
)

# Maximum characters to include per canonical doc in llms-full.txt.
# None = no limit. Reduce if you hit context-window limits.
LLMS_FULL_DOC_MAX_CHARS: int | None = None

# Maximum characters per feature packet file in llms-full.txt.
LLMS_FULL_PACKET_MAX_CHARS: int | None = 8000

# ---------------------------------------------------------------------------
# END CONFIG
# ---------------------------------------------------------------------------

AUTO_START  = ("<!-- AUTO:START - generated by build_context_pack.py; "
               "edit PROJECT_STATE.json, not here -->")
AUTO_END    = "<!-- AUTO:END -->"
HUMAN_START = "<!-- HUMAN:START -->"
HUMAN_END   = "<!-- HUMAN:END -->"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_state() -> dict:
    if not STATE.exists():
        raise SystemExit(
            "PROJECT_STATE.json not found — create it before building the "
            "context pack.")
    return json.loads(STATE.read_text(encoding="utf-8"))


def read_text(rel_or_abs: str | Path,
              max_chars: int | None = None) -> str:
    """Read a file relative to REPO_ROOT (or as absolute path)."""
    p = Path(rel_or_abs)
    if not p.is_absolute():
        p = REPO_ROOT / p
    if not p.exists():
        return f"[MISSING: {rel_or_abs}]"
    data = p.read_text(encoding="utf-8", errors="replace")
    if max_chars is not None and len(data) > max_chars:
        return data[:max_chars].rstrip() + "\n\n[truncated by context pack]\n"
    return data


def canonical_doc_paths(state: dict) -> list[Path]:
    return [REPO_ROOT / d["path"] for d in state.get("canonical_docs", [])]


def active_packet_dirs(state: dict) -> list[Path]:
    return [REPO_ROOT / p["path"]
            for p in state.get("active_feature_packets", [])
            if p.get("path")]


def ratified_spec_paths(state: dict) -> list[Path]:
    """Ratified capability specs (substrate v2.2). Empty pre-v2.2."""
    return [REPO_ROOT / s["path"]
            for s in state.get("ratified_specs", [])
            if s.get("path")]


def pack_inputs_hash(state: dict) -> str:
    """Hash the SOURCE inputs that drive generation.

    AGENT_CONTEXT.md and SOURCE_MAP.md are excluded: they are generated
    OUTPUTs, so including them would cause the freshness hash to chase a
    moving target and flag harmless human-region edits as drift.
    """
    generated_outputs = {CTX.resolve(), SOURCE_MAP.resolve()}
    h = hashlib.sha256()
    h.update(STATE.read_bytes())
    if INDEX_JSON.exists():
        h.update(INDEX_JSON.read_bytes())
    for p in canonical_doc_paths(state):
        if p.resolve() in generated_outputs:
            continue
        if p.exists():
            h.update(p.name.encode())
            h.update(p.read_bytes())
    for p in ratified_spec_paths(state):
        if p.exists():
            h.update(p.name.encode())
            h.update(p.read_bytes())
    for d in active_packet_dirs(state):
        for fname in PACKET_FILES:
            fp = d / fname
            if fp.exists():
                h.update(fp.name.encode())
                h.update(fp.read_bytes())
    return h.hexdigest()


# ---------------------------------------------------------------------------
# AGENT_CONTEXT.md — AUTO + HUMAN dual zone
# ---------------------------------------------------------------------------

def render_auto(state: dict) -> str:
    proj    = state.get("project", {})
    posture = state.get("strategic_posture", {})
    focus   = state.get("current_focus", {})
    lines = [
        AUTO_START,
        f"# {proj.get('name', 'PROJECT')} — Agent Context (start here)",
        "",
        f"**One-liner:** {proj.get('one_liner', '')}",
        f"**Stage:** `{state.get('current_stage', '')}`"
        f"  ·  **Slug:** `{proj.get('slug', '')}`",
    ]
    if proj.get("market"):
        lines.append(f"**Market:** {proj['market']}")
    lines.append("")

    if posture:
        lines += ["## North star", ""]
        if posture.get("north_star"):
            lines.append(f"- **North star:** {posture['north_star']}")
        if posture.get("hard_promise"):
            lines.append(f"- **Hard promise:** {posture['hard_promise']}")
        if posture.get("wedge"):
            lines.append(f"- **Wedge:** {posture['wedge']}")
        if posture.get("what_it_is_not"):
            lines.append("- **What it is NOT:** "
                         + "; ".join(posture["what_it_is_not"]))
        lines.append("")

    if focus.get("primary"):
        lines += ["## Current goal", "", focus["primary"], ""]
    if focus.get("next_product_slice"):
        lines += ["Next product slice:", "", focus["next_product_slice"], ""]

    lines += ["## Read order", ""]
    for i, step in enumerate([
        "PROJECT_STATE.json (machine source of truth)",
        "this file (AGENT_CONTEXT.md)",
        "VISION.md",
        "BUILD_SPEC.md",
        "the active feature packet (next_product_slice below)",
        "docs/DOCUMENT_INDEX.md only for primary evidence",
    ], 1):
        lines.append(f"{i}. {step}")

    if state.get("source_of_truth_order"):
        lines += ["", "## Source-of-truth order (conflicts: earlier wins)", ""]
        for i, s in enumerate(state["source_of_truth_order"], 1):
            lines.append(f"{i}. {s}")

    if state.get("canonical_docs"):
        lines += ["", "## Canonical docs", ""]
        for d in state["canonical_docs"]:
            must = " *(must-read)*" if d.get("must_read") else ""
            lines.append(f"- `{d['path']}` — {d.get('role', '')}{must}")

    if state.get("ratified_specs"):
        lines += ["", "## Capability specs (ratified = current behavior)", ""]
        for s in state["ratified_specs"]:
            st = s.get("status", "")
            tag = "" if st == "ratified" else f"  -- NOT current ({st})"
            lines.append(f"- `{s['path']}` — capability "
                         f"`{s.get('capability', '')}` [{st}]{tag}")

    if state.get("active_feature_packets"):
        lines += ["", "## Active feature packets", ""]
        for p in state["active_feature_packets"]:
            lines.append(f"- `{p.get('path', '?')}` — "
                         f"[{p.get('status', '?')}] {p.get('summary', '')}")

    nxt = state.get("next_product_slice", {})
    if nxt:
        lines += ["", "## Next product slice",
                  f"- **{nxt.get('packet_id', '?')}**: "
                  f"{nxt.get('summary', '')}"]

    for item in state.get("do_not_start", []):
        pass  # rendered in block below if list non-empty
    if state.get("do_not_start"):
        lines += ["", "## Do NOT start yet", ""]
        for item in state["do_not_start"]:
            lines.append(f"- {item.get('item', '')} — "
                         f"_{item.get('reason', '')}_")

    if state.get("commands"):
        lines += ["", "## Commands", ""]
        for name, cmd in state["commands"].items():
            lines.append(f"- `{name}`: `{cmd}`")

    if state.get("agent_rules"):
        lines += ["", "## Hard agent rules", ""]
        for r in state["agent_rules"]:
            lines.append(f"- {r}")

    lines += ["", AUTO_END]
    return "\n".join(lines)


def existing_human_block() -> str:
    if CTX.exists():
        txt = CTX.read_text(encoding="utf-8")
        if HUMAN_START in txt and HUMAN_END in txt:
            return txt.split(HUMAN_START, 1)[1].split(HUMAN_END, 1)[0]
    return ("\n\n_Hand-authored orientation goes here (narrative the "
            "structured state cannot capture). This region is preserved "
            "across regeneration._\n\n")


def write_context(state: dict) -> None:
    auto  = render_auto(state)
    human = existing_human_block()
    CTX.parent.mkdir(parents=True, exist_ok=True)
    CTX.write_text(f"{auto}\n\n{HUMAN_START}{human}{HUMAN_END}\n",
                   encoding="utf-8")


# ---------------------------------------------------------------------------
# SOURCE_MAP.md
# ---------------------------------------------------------------------------

def classify_document(doc: dict, state: dict) -> str:
    """Classify a document entry from DOCUMENT_INDEX against PROJECT_STATE.

    PORTING: extend the middle section with project-specific path prefixes
    that carry semantic meaning in your repo layout.
    """
    path = doc["path"]
    canonical = {item["path"]: item.get("status", "canonical")
                 for item in state.get("canonical_docs", [])}
    superseded = {item["path"]
                  for item in state.get("historical_or_superseded_docs", [])}
    historical  = {item["path"]
                   for item in state.get("historical_docs", [])}
    active_dirs = [
        p["path"].rstrip("/") + "/"
        for p in state.get("active_feature_packets", [])
        if p.get("path")
    ]

    if path in canonical:
        return canonical[path]
    if path in superseded or path in historical:
        return "superseded"
    if any(path.startswith(d) for d in active_dirs):
        return "active-feature-packet"
    if path.startswith("specs/"):
        return "ratified-spec"
    if path.startswith("docs/features/_template/"):
        return "feature-template"
    if path.startswith("docs/context/"):
        return "generated-canonical"
    if path.startswith("docs/review-batch/"):
        return "review-evidence"
    if path.startswith("docs/superpowers/specs/"):
        return "locked-spec-evidence"
    if path.startswith("docs/superpowers/plans/"):
        return "plan-evidence"
    if path.startswith("tmp/"):
        return "temporary"
    if path.startswith(".remember/"):
        return "local-memory"
    if path.startswith("research/"):
        return "research-evidence"
    if path.endswith(".png"):
        return "visual-evidence"
    return "evidence"


def write_source_map(state: dict) -> None:
    if not INDEX_JSON.exists():
        SOURCE_MAP.write_text(
            "# Source Map\n\ndocs/DOCUMENT_INDEX.json not yet generated.\n",
            encoding="utf-8")
        return

    index = json.loads(INDEX_JSON.read_text(encoding="utf-8"))
    documents = index.get("documents") or index.get("files", [])
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    rows = []
    counts: Counter = Counter()
    families: dict[str, Counter] = defaultdict(Counter)
    for doc in documents:
        status = classify_document(doc, state)
        counts[status] += 1
        families[status][doc.get("family", "unknown")] += 1
        rows.append((status, doc))

    proj_name = state.get("project", {}).get("name", "project")
    lines = [
        f"# {proj_name} Source Map",
        "",
        "Status: generated",
        f"Generated: {generated_at}",
        "",
        ("This file classifies the indexed document corpus for agent use. "
         "Generated from `PROJECT_STATE.json` and `docs/DOCUMENT_INDEX.json`."),
        "",
        "## Counts",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status, count in sorted(counts.items(),
                                key=lambda x: (-x[1], x[0])):
        lines.append(f"| `{status}` | {count} |")

    lines.extend(["", "## Canonical must-read docs", ""])
    for item in state.get("canonical_docs", []):
        if item.get("must_read"):
            lines.append(f"- `{item['path']}` — {item['role']} "
                         f"({item.get('status', '')})")

    hist = state.get("historical_or_superseded_docs",
                     state.get("historical_docs", []))
    if hist:
        lines.extend(["", "## Superseded or historical docs", ""])
        for item in hist:
            reason = item.get("reason") or item.get("note") or item.get("status", "")
            lines.append(f"- `{item['path']}` — {reason}")

    lines.extend(["", "## Full inventory classification", ""])
    current_status = None
    for status, doc in sorted(rows,
                               key=lambda x: (x[0], x[1]["path"].lower())):
        if status != current_status:
            current_status = status
            lines.extend(["", f"### {status}", ""])
        title = str(doc.get("title") or Path(doc["path"]).name).replace("|", "\\|")
        lines.append(
            f"- `{doc['path']}` — {title} "
            f"({doc.get('extension', '')}, {doc.get('size_kib', 0)} KiB)"
        )

    SOURCE_MAP.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# llms.txt
# ---------------------------------------------------------------------------

def write_llms(state: dict) -> None:
    proj    = state.get("project", {})
    posture = state.get("strategic_posture", {})
    name    = proj.get("name", "PROJECT")
    lines = [
        f"# {name}",
        "",
        f"> {proj.get('one_liner', '')}",
        "",
    ]
    if posture.get("north_star") or posture.get("hard_promise"):
        lines.append(
            f"North star: {posture.get('north_star', '')}. "
            f"Hard promise: {posture.get('hard_promise', '')}."
        )
        lines.append("")

    lines += ["## Canonical docs", ""]
    for d in state.get("canonical_docs", []):
        lines.append(f"- [{Path(d['path']).stem}]({d['path']}): "
                     f"{d.get('role', '')}")

    if state.get("ratified_specs"):
        lines += ["", "## Capability specs (ratified = current behavior)", ""]
        for s in state["ratified_specs"]:
            label = s.get("capability") or Path(s["path"]).parent.name
            st = s.get("status", "")
            note = "current behavior" if st == "ratified" else f"{st} — NOT current"
            lines.append(f"- [{label}]({s['path']}): {note}")

    if state.get("active_feature_packets"):
        lines += ["", "## Feature packets", ""]
        for p in state["active_feature_packets"]:
            req = f"{p['path'].rstrip('/')}/requirements.md"
            lines.append(f"- [{p.get('id', p['path'])}]({req}): "
                         f"{p.get('summary', '')}")

    lines += [
        "",
        "## Operating layer",
        "- [AGENTS.md](AGENTS.md): vendor-neutral agent instructions",
        "- [REVIEW.md](REVIEW.md): four-tier review gates",
        "",
        "## Generated context",
        "- [Agent context](docs/context/AGENT_CONTEXT.md): "
        "compact orientation for coding agents",
        "- [Source map](docs/context/SOURCE_MAP.md): "
        "corpus classification",
        "- [Full context](llms-full.txt): "
        "single-file export of canonical context + active packets",
    ]
    if INDEX_JSON.exists():
        lines.append("- [Document index](docs/DOCUMENT_INDEX.md): "
                     "semantic index of the document corpus")

    LLMS.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# llms-full.txt  (improvement: includes active feature packet files)
# ---------------------------------------------------------------------------

def _section(label: str, content: str) -> str:
    sep = "=" * 78
    return f"\n{sep}\n# FILE: {label}\n{sep}\n\n{content}"


def write_llms_full(state: dict) -> None:
    proj_name = state.get("project", {}).get("name", "PROJECT")
    parts = [
        f"# {proj_name} — full context bundle",
        "# Generated by tools/context/build_context_pack.py.",
        "# Canonical docs + active feature packets for single-shot LLM ingestion.",
        "# Prefer editing source files, then rerun build_context_pack.py.",
        "",
    ]

    # 1. Canonical docs (the original set)
    for d in state.get("canonical_docs", []):
        content = read_text(d["path"], LLMS_FULL_DOC_MAX_CHARS)
        parts.append(_section(f"{d['path']}  ({d.get('role', '')})", content))

    # 1b. Capability specs — only 'ratified' is current behavior (substrate v2.2).
    for s in state.get("ratified_specs", []):
        st = s.get("status", "")
        content = read_text(s["path"], LLMS_FULL_DOC_MAX_CHARS)
        if st == "ratified":
            hdr = (f"RATIFIED SPEC (current behavior): {s['path']}  "
                   f"(capability {s.get('capability', '')})")
        else:
            hdr = (f"{st.upper()} SPEC — NOT current behavior: {s['path']}  "
                   f"(capability {s.get('capability', '')})")
        parts.append(_section(hdr, content))

    # 2. Active feature packets — each packet's files concatenated.
    #    This is the NEW behaviour: prior versions omitted packet content,
    #    leaving single-shot ingestion incomplete for in-flight work.
    for pkt in state.get("active_feature_packets", []):
        pkt_path = pkt.get("path", "")
        pkt_dir  = REPO_ROOT / pkt_path
        pkt_label = (f"FEATURE PACKET: {pkt.get('id', pkt_path)} — "
                     f"{pkt.get('summary', '')}")
        parts.append(f"\n{'#' * 78}\n# {pkt_label}\n{'#' * 78}")
        for fname in PACKET_FILES:
            fp = pkt_dir / fname
            if fp.exists():
                content = read_text(fp, LLMS_FULL_PACKET_MAX_CHARS)
                parts.append(_section(f"{pkt_path}/{fname}", content))
            else:
                parts.append(_section(f"{pkt_path}/{fname}",
                                      f"[MISSING: {pkt_path}/{fname}]"))

    LLMS_FULL.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate the project agent context pack.")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the pack is stale vs its inputs")
    args = ap.parse_args()

    state   = load_state()
    current = pack_inputs_hash(state)

    if args.check:
        recorded = (HASH_FILE.read_text(encoding="utf-8").strip()
                    if HASH_FILE.exists() else "")
        if recorded != current:
            print("DRIFT: context pack is stale — run build_context_pack.py",
                  file=sys.stderr)
            return 1
        print("context pack: fresh")
        return 0

    CTX.parent.mkdir(parents=True, exist_ok=True)
    write_context(state)
    write_source_map(state)
    write_llms(state)
    write_llms_full(state)
    HASH_FILE.write_text(current + "\n", encoding="utf-8")

    print(f"context pack written (inputs hash {current[:12]})")
    print(f"  {CTX.relative_to(REPO_ROOT)}")
    print(f"  {SOURCE_MAP.relative_to(REPO_ROOT)}")
    print(f"  {LLMS.relative_to(REPO_ROOT)}")
    print(f"  {LLMS_FULL.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
