apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helix-core-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argoproj.io
spec:
  project: helixforge
  source:
    repoURL: https://github.com/helixforge/helixforge.git
    targetRevision: develop
    path: infra/helm/helix-core
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: helix-core-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
